modLoader = "javafml"
loaderVersion = "[38,)"
license = "GPLv3"

[[mods]]
modId = "minegpt"
version = "${version}"
displayName = "MineGPT"
displayURL = "https://github.com/MCTeamPotato/MineGPT"
logoFile = "icon.png"
authors = "TeamPotato, Awei, TexTrue"
description = '''
Chat with ChatGPT in Minecraft.
'''

[[dependencies.minegpt]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.minegpt]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,1.18.2]"
ordering = "NONE"
side = "BOTH"

[[dependencies.minegpt]]
modId = "architectury"
mandatory = true
versionRange = "[3,4)"
ordering = "AFTER"
side = "BOTH"